version: "3.9"

services:
  db:
    image: postgres:17
    env_file: ./.env
    environment:
      - POSTGRES_DB=$POSTGRESQL_DB
      - POSTGRES_USER=$POSTGRESQL_USER
      - POSTGRES_PASSWORD=$POSTGRESQL_PASSWORD
    ports:
      - $POSTGRESQL_LOCAL_PORT:$POSTGRESQL_DOCKER_PORT
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: