spring:
  application:
    name: otp-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:25432/otp_service
    username: klimov
    password: java
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.ethereal.email
    port: 587
    username: monique.reynolds@ethereal.email
    password: rgxJuRerQ74yBM6uRD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false

app:
  jwt:
    secret: mephi
    token-expiration-milliseconds: 3600000